### ISSUE TITLE
If it is possible to publish Keras-based version

### ISSUE THREAD

**Issue by bingothreed** [fg91/visualizing-cnn-feature-maps#3]
Visualizing is really useful for understanding what the model learned.  I just want to reimplement it  with Keras, but failed. Could you please publish a Keras version in the future?
Thank you very much ^_^

**Comment by fg91** [comment]
Hey,
thank you for your interest in this project! I am currently not planning on releasing a Keras version of this, I'm sorry. However, I am very willing to help you figure out how to reimplement it if you are interested!

**Comment by bingothreed** [comment]
@fg91 Thank you, I will try my best at first.  The theory is not too complex but really useful which I have seen in you Blog.

**Comment by fg91** [comment]
@1165048017 Ok, let me know if I can be of any assistance!

**Comment by kripanshu** [comment]
I used this https://blog.keras.io/how-convolutional-neural-networks-see-the-world.html to reproduce the keras implementation, but the results are not good as yours. Can you suggest any changes to the blog.
Thank you.

**Comment by fg91** [comment]
Hey,
In my opinion, the progressive resizing and intermediate blurring I described in the blog post is crucial. Did you implement this in the Keras version?

**Comment by bingothreed** [comment]
@fg91 Fortunately，@raghakot had already implemented the Keras-based version named `keras-vis`.
The documents can be found [here](https://raghakot.github.io/keras-vis/)
The sample code in Github can be found [here](https://github.com/fg91/visualizing-cnn-feature-maps)

The implementation is a little hard for me, though the theory is not so complex. ^_^

**Comment by kripanshu** [comment]
@fg91 I was not using progressive resizing, this along with many other factors does changed the visualization. Thanks for the suggestion. 
Also I found this keras implementation from keras team: https://keras.io/examples/conv_filter_visualization/
which helped a lot.

**Comment by fg91** [comment]
I'm happy to hear that!
Best regards,
Fabio
