### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by Light--** [fg91/visualizing-cnn-feature-maps#4]
when i run the "filter_visualizer.ipynb"  on cpu mac osx

i already removed cuda in the 2 line codes below to use cpu:

self.features = torch.tensor(output,requires_grad=True)

self.model = vgg16(pre=True).eval()

but still got a error:

---> 21                 self.model(img_var)

How can i call a pretrained model using fastai？..

why it says "TypeError: 'module' object is not callable" ......

Full errors：

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-153-818a4416ad1d> in <module>
      3 
      4 FV = FilterVisualizer(size=56, upscaling_steps=12, upscaling_factor=1.2)
----> 5 FV.visualize(layer, filter, blur=5)
      6 
      7 img = PIL.Image.open("layer_"+str(layer)+"_filter_"+str(filter)+".jpg")

<ipython-input-152-f12949eac886> in visualize(self, layer, filter, lr, opt_steps, blur)
     19                 optimizer.zero_grad()
     20 
---> 21                 self.model(img_var)
     22 
     23                 loss = -activations.features[0, filter].mean()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    355                 arg_reprs.append("{}={}".format(key, val))
    356             return ValueError('module.to expects .to(device), .to(dtype) or '
--> 357                               '.to(device, dtype), where dtype is a floating '
    358                               'point type, but got .to({})'
    359                               .format(", ".join(arg_reprs)))

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/container.py in forward(self, input)
     65             return Sequential(OrderedDict(list(self._modules.items())[idx]))
     66         else:
---> 67             return self._get_item_by_idx(self._modules.values(), idx)
     68 
     69     def __setitem__(self, idx, module):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    357                               '.to(device, dtype), where dtype is a floating '
    358                               'point type, but got .to({})'
--> 359                               .format(", ".join(arg_reprs)))
    360 
    361         nargs = len(args) + len(kwargs)

<ipython-input-151-0b9a265dc517> in hook_fn(self, module, input, output)
      3         self.hook = module.register_forward_hook(self.hook_fn)
      4     def hook_fn(self, module, input, output):
----> 5         self.features = torch.tensor(output,requires_grad=True)
      6     def close(self):
      7         self.hook.remove()

TypeError: 'module' object is not callable

**Comment by nargeshn** [comment]
When I updated my Pytorch, the problem was solved. Here is the link for PyTorch:
https://discuss.pytorch.org/t/torch-tensor-doesnt-work-provides-following-error-typeerror-module-object-is-not-callable/16903

**Comment by Light--** [comment]
> When I updated my Pytorch, the problem was solved. Here is the link for PyTorch:
> https://discuss.pytorch.org/t/torch-tensor-doesnt-work-provides-following-error-typeerror-module-object-is-not-callable/16903

THX a lot. After i got this error i turned to this repo: https://github.com/fchollet/deep-learning-with-python-notebooks/blob/master/5.4-visualizing-what-convnets-learn.ipynb 
and solved.
